### PR TITLE
Character profile in dialogue box

### PR DESCRIPTION
**Pull request by Dragonlinae**
Add title and picture to dialogue box.

image

### CODE REVIEW

**Comment by NovaSagittarii** [comment]
can you take a screenshot if its easy to see :D

**Review by NovaSagittarii — CHANGES_REQUESTED** [review]
looked into this more and apparently its also on week7 branch so uhhhhhhhh

Crashing on this part when running.

```gdscript
func _on_area_exited(area):
	if get_node("Dialoguearea").spoken:
		get_node("Dialoguearea").queue_free()
		get_node("CollisionShape2D2").queue_free()
		dialogue_box = dialogue_box_scene.instantiate()
		dialogue_box.dialogues = dialogues
		add_child(dialogue_box)
		activated = true
```

image

**Review by NovaSagittarii — APPROVED** [review]
to be merged via #17

**Review by AnPhu-D — APPROVED** [review]
lgtm

**Pull request merged**
